[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@foundry-devops/=lib/foundry-devops/",
    "@openzeppelin=lib/openzeppelin-contracts",
    "@ccip/contracts=lib/ccip/contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
    "@chainlink-local=lib/chainlink-local"
]

rpc_endpoints = { eth = "http://localhost:8545", arb = "http://localhost:8546" }

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
# via_ir = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./config" },
]

# 为 CCIP 相关的文件指定 0.8.24 版本
# [[profile.default.overrides]]
# paths = ["lib/ccip/contracts/src/**/*.sol"]
# solc_version = "0.8.24"

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable"]
